# -*- coding: utf-8 -*-
"""
Created on Tue Jul  6 14:34:22 2021

@author: Christopher

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def evenfib(n):
    """Sum even-valued fibonacci numbers"""
    total = 0
    a = 0
    b = 1
    while b < n:
        if b % 2 == 0:
            total = total + b
            a, b = b, a + b
        else:
            a, b = b, b + a
    print(total)